import { Typography } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import { useSelector } from "react-redux";
import styles from "../styles/Home.module.css";

export default function Home() {
  const reduxValue = useSelector((state) => state.counter.value);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Typography variant="h3" className="text-center">
        This is index page - {reduxValue}
      </Typography>
    </div>
  );
}
